global_costmap:
  obstacle_range: 1.0
  raytrace_range: 1.2
  # footprint: [[0.035, 0.065], [0.045, 0.0], [0.035, -0.065], [-0.08, -0.065], [-0.08, 0.065]]
  footprint_padding: 0.01
  robot_radius: 0.05
  transform_tolerance: 0.5

  update_frequency: 3.0
  publish_frequency: 2.0

  resolution: 0.05

  global_frame: map
  robot_base_frame: base_link

  rolling_window: false

  # width: 50.0
  # height: 50.0
  # static_map: true
  origin_x: 0
  origin_y: 0
  # robot_radius: 0.05
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

static_layer:
  unknown_cost_value: 0
  lethal_cost_threshold: 253
  map_topic: /map
  first_map_only: false
  static_map: true

obstacle_layer:
  combination_method: 1
  observation_sources: laser_scan_sensor
  track_unknown_space: true
  map_type: costmap
  laser_scan_sensor:
    sensor_frame: laser_frame
    topic: scan
    data_type: LaserScan
    marking: true
    clearing: false

inflation_layer:
  inflation_radius: 0.30
  cost_scaling_factor: 6.0