# GMapping params:
base_frame: base_link
map_frame: world
odom_frame: odom

throttle_scans: 1.0
map_update_interval: 2.0            # Consider
maxUrange: 1.5                      # Consider
sigma: 0.05                         # Used in optimization
kernelSize: 1                       # Used in optimization
lstep: 0.05                         # Used in optimization
astep: 0.05                         # Used in optimization
iterations: 5                       # Used in optimization
lsigma: 0.075                       # Used in optimization
ogain: 3.0                          # Used in optimization
lskip: 0
minimumScore: 0.0                   # Used in optimization
srr: 0.002                          # Used in optimization
srt: 0.002                          # Used in optimization
str: 0.002                          # Used in optimization
stt: 0.005                          # Used in optimization
linearUpdate: 0.2                   # Consider
angularUpdate: 0.5                  # Consider
temporalUpdate: -1.0
resampleThreshold: 0.5              # Used in optimization
particles: 10                      # Consider
xmin: -10.0
ymin: -10.0
xmax: 10.0
ymax: 10.0
delta: 0.025                        # Consider
llsamplerange: 0.01                 # Consider
llsamplestep: 0.01                  # Consider
lasamplerange: 0.005                # Consider
lasamplestep: 0.005                 # Consider
transform_publish_period: 0.05      # Consider
occ_thresh: 0.25                    # Consider
